# Generated by Django 5.2.12 on 2026-05-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alert', '0003_alter_alert_id_alter_alert_tipo_de_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Revisada', 'Revisada'), ('Descartada', 'Descartada')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='Alert.alert', verbose_name='Alerta relacionada')),
            ],
            options={
                'db_table': 'recomendacion',
            },
        ),
    ]
