# Generated by Django 6.0.5 on 2026-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('tipo_de_alerta', models.CharField(choices=[('Humedad_alta', 'Humedad alta en el suelo'), ('Humedad_baja', 'Humedad baja en el suelo')], max_length=100, verbose_name='Tipo de alerta')),
                ('nivel', models.CharField(max_length=50, verbose_name='Nivel')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('variable_afectada', models.CharField(max_length=100, verbose_name='Variable afectada')),
            ],
            options={
                'db_table': 'alerta',
            },
        ),
    ]
