# Generated by Django 6.0.5 on 2026-05-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='nivel',
        ),
    ]
