# Generated by Django 5.2.12 on 2026-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alert', '0002_remove_alert_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='tipo_de_alerta',
            field=models.CharField(choices=[('Humedad_alta', 'Humedad alta en el suelo'), ('Humedad_baja', 'Humedad baja en el suelo'), ('Bateria_critica', 'Batería crítica'), ('Caida_bateria', 'Caída brusca de batería'), ('Panel_sin_carga', 'Panel solar sin carga y batería baja')], max_length=100, verbose_name='Tipo de alerta'),
        ),
    ]
